# Site settings
title: tophackr status
description: Information on the status of tophackr services.
baseurl: '/status-other'
url: 'https://tophackr.gitlab.io' # the base hostname & protocol for your site
repository: 'https://gitlab.com/tophackr/status-other'
email: tophackr@icloud.com
twitter: tophackrstatus
zone: 'UTC+3'

# Build settings
markdown: kramdown
timezone: Europe/Moscow
encoding: utf-8
permalink: /incidents/:title/
# limit_posts: 10
exclude: [".gitignore", README.md, CONTRIBUTING.md, Gemfile, Gemfile.lock]